// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: transcoder/v1/transcoder.proto

package transcoderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QualityProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int32                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`        // 档位高度，如 720
	Resolution    string                 `protobuf:"bytes,2,opt,name=resolution,proto3" json:"resolution,omitempty"` // 展示名，如 "720p"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualityProfile) Reset() {
	*x = QualityProfile{}
	mi := &file_transcoder_v1_transcoder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityProfile) ProtoMessage() {}

func (x *QualityProfile) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_v1_transcoder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityProfile.ProtoReflect.Descriptor instead.
func (*QualityProfile) Descriptor() ([]byte, []int) {
	return file_transcoder_v1_transcoder_proto_rawDescGZIP(), []int{0}
}

func (x *QualityProfile) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *QualityProfile) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

type ProcessVideoRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Bucket           string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`                                                 // MinIO 桶名
	ObjectKey        string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`                          // 原始视频 object key（如 raw/xxx.mp4）
	OutputPrefix     string                 `protobuf:"bytes,3,opt,name=output_prefix,json=outputPrefix,proto3" json:"output_prefix,omitempty"`                 // DASH 输出前缀（如 dash/{video_id}）
	CoverObjectKey   string                 `protobuf:"bytes,4,opt,name=cover_object_key,json=coverObjectKey,proto3" json:"cover_object_key,omitempty"`         // 封面 object key（如 covers/{video_id}.jpg）
	CoverTimeSeconds float64                `protobuf:"fixed64,5,opt,name=cover_time_seconds,json=coverTimeSeconds,proto3" json:"cover_time_seconds,omitempty"` // 抽帧时间点；0 表示自动选择
	QualityHeights   []int32                `protobuf:"varint,6,rep,packed,name=quality_heights,json=qualityHeights,proto3" json:"quality_heights,omitempty"`   // 空表示由 transcoder 自动选择 ABR 档位
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessVideoRequest) Reset() {
	*x = ProcessVideoRequest{}
	mi := &file_transcoder_v1_transcoder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessVideoRequest) ProtoMessage() {}

func (x *ProcessVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_v1_transcoder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessVideoRequest.ProtoReflect.Descriptor instead.
func (*ProcessVideoRequest) Descriptor() ([]byte, []int) {
	return file_transcoder_v1_transcoder_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessVideoRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ProcessVideoRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ProcessVideoRequest) GetOutputPrefix() string {
	if x != nil {
		return x.OutputPrefix
	}
	return ""
}

func (x *ProcessVideoRequest) GetCoverObjectKey() string {
	if x != nil {
		return x.CoverObjectKey
	}
	return ""
}

func (x *ProcessVideoRequest) GetCoverTimeSeconds() float64 {
	if x != nil {
		return x.CoverTimeSeconds
	}
	return 0
}

func (x *ProcessVideoRequest) GetQualityHeights() []int32 {
	if x != nil {
		return x.QualityHeights
	}
	return nil
}

type ProcessVideoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DurationSeconds   float64                `protobuf:"fixed64,1,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	ManifestObjectKey string                 `protobuf:"bytes,2,opt,name=manifest_object_key,json=manifestObjectKey,proto3" json:"manifest_object_key,omitempty"`
	ManifestSize      int64                  `protobuf:"varint,3,opt,name=manifest_size,json=manifestSize,proto3" json:"manifest_size,omitempty"`
	CoverObjectKey    string                 `protobuf:"bytes,4,opt,name=cover_object_key,json=coverObjectKey,proto3" json:"cover_object_key,omitempty"` // 空表示未生成封面
	CoverSize         int64                  `protobuf:"varint,5,opt,name=cover_size,json=coverSize,proto3" json:"cover_size,omitempty"`
	Profiles          []*QualityProfile      `protobuf:"bytes,6,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProcessVideoResponse) Reset() {
	*x = ProcessVideoResponse{}
	mi := &file_transcoder_v1_transcoder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessVideoResponse) ProtoMessage() {}

func (x *ProcessVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_v1_transcoder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessVideoResponse.ProtoReflect.Descriptor instead.
func (*ProcessVideoResponse) Descriptor() ([]byte, []int) {
	return file_transcoder_v1_transcoder_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessVideoResponse) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *ProcessVideoResponse) GetManifestObjectKey() string {
	if x != nil {
		return x.ManifestObjectKey
	}
	return ""
}

func (x *ProcessVideoResponse) GetManifestSize() int64 {
	if x != nil {
		return x.ManifestSize
	}
	return 0
}

func (x *ProcessVideoResponse) GetCoverObjectKey() string {
	if x != nil {
		return x.CoverObjectKey
	}
	return ""
}

func (x *ProcessVideoResponse) GetCoverSize() int64 {
	if x != nil {
		return x.CoverSize
	}
	return 0
}

func (x *ProcessVideoResponse) GetProfiles() []*QualityProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

var File_transcoder_v1_transcoder_proto protoreflect.FileDescriptor

const file_transcoder_v1_transcoder_proto_rawDesc = "" +
	"\n" +
	"\x1etranscoder/v1/transcoder.proto\x12\rtranscoder.v1\"H\n" +
	"\x0eQualityProfile\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x05R\x06height\x12\x1e\n" +
	"\n" +
	"resolution\x18\x02 \x01(\tR\n" +
	"resolution\"\xf2\x01\n" +
	"\x13ProcessVideoRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12#\n" +
	"\routput_prefix\x18\x03 \x01(\tR\foutputPrefix\x12(\n" +
	"\x10cover_object_key\x18\x04 \x01(\tR\x0ecoverObjectKey\x12,\n" +
	"\x12cover_time_seconds\x18\x05 \x01(\x01R\x10coverTimeSeconds\x12'\n" +
	"\x0fquality_heights\x18\x06 \x03(\x05R\x0equalityHeights\"\x9a\x02\n" +
	"\x14ProcessVideoResponse\x12)\n" +
	"\x10duration_seconds\x18\x01 \x01(\x01R\x0fdurationSeconds\x12.\n" +
	"\x13manifest_object_key\x18\x02 \x01(\tR\x11manifestObjectKey\x12#\n" +
	"\rmanifest_size\x18\x03 \x01(\x03R\fmanifestSize\x12(\n" +
	"\x10cover_object_key\x18\x04 \x01(\tR\x0ecoverObjectKey\x12\x1d\n" +
	"\n" +
	"cover_size\x18\x05 \x01(\x03R\tcoverSize\x129\n" +
	"\bprofiles\x18\x06 \x03(\v2\x1d.transcoder.v1.QualityProfileR\bprofiles2l\n" +
	"\x11TranscoderService\x12W\n" +
	"\fProcessVideo\x12\".transcoder.v1.ProcessVideoRequest\x1a#.transcoder.v1.ProcessVideoResponseBLZJgithub.com/binhy/vistack/internal/transcoder/pb/transcoder/v1;transcoderpbb\x06proto3"

var (
	file_transcoder_v1_transcoder_proto_rawDescOnce sync.Once
	file_transcoder_v1_transcoder_proto_rawDescData []byte
)

func file_transcoder_v1_transcoder_proto_rawDescGZIP() []byte {
	file_transcoder_v1_transcoder_proto_rawDescOnce.Do(func() {
		file_transcoder_v1_transcoder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transcoder_v1_transcoder_proto_rawDesc), len(file_transcoder_v1_transcoder_proto_rawDesc)))
	})
	return file_transcoder_v1_transcoder_proto_rawDescData
}

var file_transcoder_v1_transcoder_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_transcoder_v1_transcoder_proto_goTypes = []any{
	(*QualityProfile)(nil),       // 0: transcoder.v1.QualityProfile
	(*ProcessVideoRequest)(nil),  // 1: transcoder.v1.ProcessVideoRequest
	(*ProcessVideoResponse)(nil), // 2: transcoder.v1.ProcessVideoResponse
}
var file_transcoder_v1_transcoder_proto_depIdxs = []int32{
	0, // 0: transcoder.v1.ProcessVideoResponse.profiles:type_name -> transcoder.v1.QualityProfile
	1, // 1: transcoder.v1.TranscoderService.ProcessVideo:input_type -> transcoder.v1.ProcessVideoRequest
	2, // 2: transcoder.v1.TranscoderService.ProcessVideo:output_type -> transcoder.v1.ProcessVideoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transcoder_v1_transcoder_proto_init() }
func file_transcoder_v1_transcoder_proto_init() {
	if File_transcoder_v1_transcoder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transcoder_v1_transcoder_proto_rawDesc), len(file_transcoder_v1_transcoder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transcoder_v1_transcoder_proto_goTypes,
		DependencyIndexes: file_transcoder_v1_transcoder_proto_depIdxs,
		MessageInfos:      file_transcoder_v1_transcoder_proto_msgTypes,
	}.Build()
	File_transcoder_v1_transcoder_proto = out.File
	file_transcoder_v1_transcoder_proto_goTypes = nil
	file_transcoder_v1_transcoder_proto_depIdxs = nil
}
