// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: transcoder/v1/transcoder.proto

package transcoderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TranscoderService_ProcessVideo_FullMethodName = "/transcoder.v1.TranscoderService/ProcessVideo"
)

// TranscoderServiceClient is the client API for TranscoderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TranscoderService 远程转码服务：封装 ffprobe/ffmpeg，读写 MinIO，无状态。
type TranscoderServiceClient interface {
	// ProcessVideo 下载原始视频、探测、抽封面、转码 DASH 并写回 MinIO。
	ProcessVideo(ctx context.Context, in *ProcessVideoRequest, opts ...grpc.CallOption) (*ProcessVideoResponse, error)
}

type transcoderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTranscoderServiceClient(cc grpc.ClientConnInterface) TranscoderServiceClient {
	return &transcoderServiceClient{cc}
}

func (c *transcoderServiceClient) ProcessVideo(ctx context.Context, in *ProcessVideoRequest, opts ...grpc.CallOption) (*ProcessVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessVideoResponse)
	err := c.cc.Invoke(ctx, TranscoderService_ProcessVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TranscoderServiceServer is the server API for TranscoderService service.
// All implementations must embed UnimplementedTranscoderServiceServer
// for forward compatibility.
//
// TranscoderService 远程转码服务：封装 ffprobe/ffmpeg，读写 MinIO，无状态。
type TranscoderServiceServer interface {
	// ProcessVideo 下载原始视频、探测、抽封面、转码 DASH 并写回 MinIO。
	ProcessVideo(context.Context, *ProcessVideoRequest) (*ProcessVideoResponse, error)
	mustEmbedUnimplementedTranscoderServiceServer()
}

// UnimplementedTranscoderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranscoderServiceServer struct{}

func (UnimplementedTranscoderServiceServer) ProcessVideo(context.Context, *ProcessVideoRequest) (*ProcessVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessVideo not implemented")
}
func (UnimplementedTranscoderServiceServer) mustEmbedUnimplementedTranscoderServiceServer() {}
func (UnimplementedTranscoderServiceServer) testEmbeddedByValue()                           {}

// UnsafeTranscoderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranscoderServiceServer will
// result in compilation errors.
type UnsafeTranscoderServiceServer interface {
	mustEmbedUnimplementedTranscoderServiceServer()
}

func RegisterTranscoderServiceServer(s grpc.ServiceRegistrar, srv TranscoderServiceServer) {
	// If the following call pancis, it indicates UnimplementedTranscoderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TranscoderService_ServiceDesc, srv)
}

func _TranscoderService_ProcessVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscoderServiceServer).ProcessVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscoderService_ProcessVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscoderServiceServer).ProcessVideo(ctx, req.(*ProcessVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TranscoderService_ServiceDesc is the grpc.ServiceDesc for TranscoderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TranscoderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transcoder.v1.TranscoderService",
	HandlerType: (*TranscoderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessVideo",
			Handler:    _TranscoderService_ProcessVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transcoder/v1/transcoder.proto",
}
