[minio]
endpoint = "localhost:2591"
public_endpoint = "localhost:2591" # Public address for frontend (e.g. minio.example.com)
access_key = "minioadmin"
secret_key = "c9jA9ZvNXLwfs6n6fog6EJ0396Q77TbEm6G1XeDQbFG02GYwBsMh5wcTeJFzquD6sYE5saMGsrLnXernC5VaxjNfUuKqZxGRh9wf"
secure = false
bucket = "vistack"

[database]
host = "localhost"
port = 5432
user = "postgres"
password  = "postgres"
name = "postgres"
max_idle_conns = 10
max_open_conns = 100
conn_max_lifetime = 3600

[server]
port = 8080
host = "0.0.0.0"

[auth]
jwt_secret = "secret"
jwt_expiration = 3600

[redis]
host = "127.0.0.1"
port = 6379
db = 0
password = ""
pool_size = 10

[snowflake]
node_id = 1

[kafka]
brokers = ["localhost:9092"]
group_id = "vistack-consumer-group"

[cors]
enable = true
allow_origins = ["http://localhost:8335", "http://localhost:8336"]
allow_methods = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
allow_headers = ["Content-Type", "Authorization", "X-Requested-With"]
allow_credentials = true
